export declare const swap: string;
export declare const swapBody: string;
export declare const swapBodyButton: string;
export declare const swapBodyButtondisabled: string;
export declare const swapBodyDetails: string;
export declare const swapBodyDetailsItem: string;
export declare const swapBodyDetailsItemKey: string;
export declare const swapBodyDetailsItemValue: string;
export declare const swapBodyExchange: string;
export declare const swapBodyExchangeIcon: string;
export declare const swapBodyInputareaBody: string;
export declare const swapBodyInputareaBodyDropdown: string;
export declare const swapBodyInputareaBodyDropdownItem: string;
export declare const swapBodyInputareaBodyDropdownItemImg: string;
export declare const swapBodyInputareaBodyDropdownItemLeft: string;
export declare const swapBodyInputareaBodyDropdownItemLeftName: string;
export declare const swapBodyInputareaBodyDropdownItemLeftSymbol: string;
export declare const swapBodyInputareaBodyDropdownSearcharea: string;
export declare const swapBodyInputareaBodyDropdownSearchareaCtr: string;
export declare const swapBodyInputareaBodyDropdownSearchareaCtrIcon: string;
export declare const swapBodyInputareaBodyDropdownSearchareaCtrInput: string;
export declare const swapBodyInputareaBodyDropdownactive: string;
export declare const swapBodyInputareaBodyTokenselector: string;
export declare const swapBodyInputareaBodyTokenselectorIcon: string;
export declare const swapBodyInputareaBodyTokenselectorImg: string;
export declare const swapBodyInputareaBodyTokenselectorSymbol: string;
export declare const swapBodyInputareaInfo: string;
export declare const swapBodyInputareaLabel: string;
export declare const swapBodySettings: string;
export declare const swapHeader: string;
export declare const swapHeaderSettings: string;

declare const ClassNames: {
  "swap": string;
  "swapBody": string;
  "swapBodyButton": string;
  "swapBodyButtondisabled": string;
  "swapBodyDetails": string;
  "swapBodyDetailsItem": string;
  "swapBodyDetailsItemKey": string;
  "swapBodyDetailsItemValue": string;
  "swapBodyExchange": string;
  "swapBodyExchangeIcon": string;
  "swapBodyInputareaBody": string;
  "swapBodyInputareaBodyDropdown": string;
  "swapBodyInputareaBodyDropdownItem": string;
  "swapBodyInputareaBodyDropdownItemImg": string;
  "swapBodyInputareaBodyDropdownItemLeft": string;
  "swapBodyInputareaBodyDropdownItemLeftName": string;
  "swapBodyInputareaBodyDropdownItemLeftSymbol": string;
  "swapBodyInputareaBodyDropdownSearcharea": string;
  "swapBodyInputareaBodyDropdownSearchareaCtr": string;
  "swapBodyInputareaBodyDropdownSearchareaCtrIcon": string;
  "swapBodyInputareaBodyDropdownSearchareaCtrInput": string;
  "swapBodyInputareaBodyDropdownactive": string;
  "swapBodyInputareaBodyTokenselector": string;
  "swapBodyInputareaBodyTokenselectorIcon": string;
  "swapBodyInputareaBodyTokenselectorImg": string;
  "swapBodyInputareaBodyTokenselectorSymbol": string;
  "swapBodyInputareaInfo": string;
  "swapBodyInputareaLabel": string;
  "swapBodySettings": string;
  "swapHeader": string;
  "swapHeaderSettings": string;
};
export default ClassNames;